name: firebase_data_connect
description: "Firebase Data Connect"
version: 0.0.1
homepage: https://firebase.google.com/docs/data-connect/quickstart?platform=flutter

false_secrets:
  - example/**
  - dartpad/**

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  firebase_app_check: ^0.3.0+3
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  firebase_core_platform_interface: ^5.1.0
  flutter:
    sdk: flutter
  grpc: ^3.2.4
  http: ^1.2.1
  protobuf: ^3.1.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  plugin_platform_interface: ^2.1.3
